name: Deployment
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'run tests'

  deploy-dev:
    name: Dev deployment
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'dev deployment'

  deploy-production:
    name: Prod deployment
    needs: deploy-dev
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'production deployment'
